spring:
  application:
    name: device-backend
  data:
    mongodb:
      database: device
      auto-index-creation: true
#  security:
#    user:
#      name: admin
#      password: pass
#      roles: ADMIN
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java:
      version: @java.version@
  build-timestamp: @maven.build.timestamp@
server:
  port: 8077
