global:
  scrape_interval: 5s #scrape every 5 seconds
  evaluation_interval: 5s #evaluate rules every 5 secs

rule_files:
#  - "one_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'device-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.178.31:8077'] #docker host and port

#    basic_auth:
#      username: "admin"
#      password: "pass"